apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: user-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: user-service
              key: spring-datasource-url
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: user-service
              key: server-port
        volumeMounts:
        - name: app-properties
          mountPath: /var/log
        image: ghcr.io/huseyinbabal/user-service:1.0.0-rc.2
        imagePullPolicy: IfNotPresent
        name: user-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
      restartPolicy: Always
      volumes:
      - name: app-properties
        configMap:
          name: app-properties
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service
  namespace: user-system
data:
  spring-datasource-url: amRiYzpteXNxbDovL2FkbWluOnNlY3JldEBteXNxbDozMzA2L215ZGI=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: user-system
data:
  server-port: "8085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: user-system
  name: app-properties
data:
  application.name: user-service
  application.port: "9097"
