
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-system
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 8080
      targetPort: 8080

