apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: "1.18.2"  # Check for latest version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
      metrics_generator:
        enabled: true
        storage:
          path: /var/tempo/generator/wal
        registry:
          enabled: true
        remote_write:
          - url: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/write    # Prometheus remote write endpoint
            send_exemplars: true
        processors:
          - service-graphs
          - span-metrics
    persistence:
      enabled: true
      size: 10Gi
    serviceMonitor:
      enabled: true  # Enables Prometheus monitoring of Tempo