apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: 'http://vault.vault.svc.cluster.local:8200'
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-unseal-keys
          key: vault-root
          namespace: vault
