apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-system
spec:
  interval: 5m
  targetNamespace: mariadb-system
  releaseName: mariadb-operator-crds
  chart:
    spec: 
      chart: mariadb-operator-crds
      version: 25.8.4
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-system
spec:
  interval: 5m
  targetNamespace: mariadb-system
  releaseName: mariadb-operator
  chart:
    spec: 
      chart: mariadb-operator
      version: 25.8.4
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 5m

