
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- database.yaml
- deployment.yaml
- service.yaml
- image-update-automation.yaml
- image-policy.yaml
- image-repository.yaml
-images:
  - name: ghcr.io/huseyinbabal/product-service
    newName: ghcr.io/huseyinbabal/product-service # {"$imagepolicy": "flux-system:product-service:name"}
    newTag: 1.0.0-rc.8 # {"$imagepolicy": "flux-system:product-service:tag"} 
