
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- database.yaml
- deployment.yaml
- service.yaml
- image-update-automation.yaml
- image-policy.yaml
- image-repository.yaml
