---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: cloudflare-credentials
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: headz/cloudflare-credentials
        property: API_TOKEN
