apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: huseyinbabal88@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: huseyinbabal88@gmail.com
            apiTokenSecretRef:
              name: cloudflare-credentials
              key: API_TOKEN