apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.27/samples/addons/prometheus.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.27/samples/addons/grafana.yaml
